import { AppException } from '../app.exception';

export class RecordatorioNaoEncontradoException extends AppException {
  constructor() {
    super('Recordatorio n√£o encontrado!', 404);
  }
}